### ISSUE TITLE
Implement the Todo Page(Stephane)

### ISSUE THREAD

**Issue by Stephboss9** [Course-Hero-3/CH3-Capstone#10]
- [x] implement the Todo form (create, update, complete)
- [x] implement the Todo list viewer component
- [x]  implement the Task-Detail component
- [x] implement onClick modal functionality
- [x] create form states for each form
- [x] create handleOnChange function to handle input changes
