### ISSUE TITLE
Permissions and Todo Model/Route (involves Task+Completed table) - KIAN

### ISSUE THREAD

**Issue by kfr7** [Course-Hero-3/CH3-Capstone#15]
- [x] Update permissions.js as needed
- [x] Make a new model for todo
- [x] Make a new route for todo
- [x] The todo model will insert into the "completed" table
- [x] The todo model will also insert, update, and delete from "tasks" table
- [x] test and make sure users can't update a different user's task
- [x] Finish get all tasks, add task, update task, delete task
- [x] Update app.js accordingly
